services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    build:
      context: .
      dockerfile: Dockerfile
      pull: true
    volumes:
      - open-webui:/app/backend/data
    ports:
      - 3000:8080
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: always
    environment:
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      OPENID_PROVIDER_URL: ${OPENID_PROVIDER_URL}
      OAUTH_MERGE_ACCOUNTS_BY_EMAIL: true
    
  hermes:
    image: nousresearch/hermes-agent:${HERMES_TAG-latest}
    volumes:
      - hermes-data:/opt/data
    ports:
      - 8642:8642
    environment:
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      API_SERVER_ENABLED: true
      API_SERVER_KEY: your-secret-key-fob!
      API_SERVER_HOST: 0.0.0.0
    command: ["gateway"]
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: always
    pull_policy: always
  openclaw:
    image: ghcr.io/openclaw/openclaw:${OPENCLAW_TAG-latest}
    build:
      context: .
      dockerfile: Dockerfile.openclaw
      pull: true
      args:
        - CLAWHUB_API_KEY=${CLAWHUB_API_KEY}
        - OPENCLAW_TAG=${OPENCLAW_TAG-latest}
    restart: always
    environment:
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
      GOOGLE_MAPS_LANG: ${GOOGLE_MAPS_LANG}
      GOOGLE_PLACES_API_KEY: ${GOOGLE_PLACES_API_KEY}
      BAIDU_API_KEY: ${BAIDU_API_KEY}
      CLAWHUB_API_KEY: ${CLAWHUB_API_KEY}
      ZHIPU_API_KEY: ${ZHIPU_API_KEY}
      OPENCLAW_NO_RESPAWN: 1
      NODE_COMPILE_CACHE: /var/tmp/openclaw-compile-cache
    volumes:
      - ./openclaw-data:/home/node/.openclaw
      - linuxbrew:/home/linuxbrew
    ports:
      - 18789:18789
    extra_hosts:
      - host.docker.internal:host-gateway

volumes:
  open-webui:
  hermes-data:
  linuxbrew:


