ARG HERMES_TAG=latest
FROM nousresearch/hermes-agent:${HERMES_TAG}
RUN apt-get update && \
   apt-get install -y  --no-install-recommends chromium  chromium-sandbox curl python3-pip && \
   apt-get clean && \
   rm -rf /tmp/* /var/tmp/* /var/lib/apt/lists/* /usr/lib/python3.*/EXTERNALLY-MANAGED
   