ARG HERMES_TAG=latest
FROM nousresearch/hermes-agent:${HERMES_TAG}
RUN apt-get install -y  --no-install-recommends curl python3-pip && \
   apt-get clean && \
   npx playwright install chromium && \
   rm -rf /tmp/* /var/tmp/* /var/lib/apt/lists/* /usr/lib/python3.*/EXTERNALLY-MANAGED /root/.cache
